name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "mail-d1"
database_id = "2888ab95-5cc6-4135-baab-fd3e8545a806"
remote = true

[[kv_namespaces]]
binding = "kv"
id = "9843c6e570a448b784f9b605511e2b32"
remote = true

[[r2_buckets]]
binding = "r2"
bucket_name = "mail-r2"
remote = true

#[ai]
#binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

#[[send_email]]
#name = "email"


[vars]
ai_model = ""
analysis_cache = false
orm_log = false
domain = ["900198.xyz", "xxzu.de", "biso.cc.cd"]
admin = "zjw@900198.xyz"
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"
